// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xosbgcmnarwhyiwnqilq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhvc2JnY21uYXJ3aHlpd25xaWxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MDM2NjAsImV4cCI6MjA2NTA3OTY2MH0.Fv0-0C52sGNZ8D80vvMBsMPywYDGHJyI5a2VZP4JH0I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});